class UserMessageUseCase {
	constructor(
		readonly sessionId: string,
		readonly message: string,
	) {}

	// todo: define a port for llm interactions, and use it in this use case to interact with the llm, instead of directly coupling the use case to a specific llm implementation
	// todo: define a proper type for the yielded events
	async *generateResponse(): AsyncGenerator<unknown> {
		// orchestrate the llm loop here, yielding sse events as they are generated by the llm
		// use sse to stream tokens, thoughts, or any other intermediate data from the llm to the client in real-time
		// no resposne is returned by this use case
	}
}

export default UserMessageUseCase;
